routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','DaruClubController@index');
Route::get('/daru-about','DaruClubController@aboutUs');
Route::get('/daru-gallery','DaruClubController@getGallery');
Route::get('/daru-partner','DaruClubController@getPartners');
Route::get('/daru-faq','DaruClubController@getFaq');
Route::get('/daru-contact','DaruClubController@contactUs');
Route::get('/daru-single','DaruClubController@getSingle');






Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.request');
Route::post('password/otp', 'Auth\ResetPasswordController@postReset')->name('password.mobile');
Route::post('password/update', 'Auth\ResetPasswordController@updatePassword')->name('password.update');
Auth::routes();
Route::post('login', 'Auth\LoginController@login');
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');
Route::get('/verifyemail/{token}', 'Auth\RegisterController@verify');
// Route::get('/home', 'HomeController@index')->name('home');
Route::post('popup/signup', 'PopupController@register');
Route::get('signup', 'PopupController@form');



Route::get('barlist', 'PopupController@form');
Route::get('bardetails', 'PopupController@form');
Route::get('bar-items', 'PopupController@form');
Route::get('bar-items/', 'PopupController@form');


Route::group(['prefix' => 'administrator', 'middleware' => ['role:admin']], function() {
	Route::resource('roles','RoleController');
	Route::resource('users','UserController');
});


Route::group(['prefix' => 'customer', 'middleware' => ['user']], function() {
	Route::get('dashboard', 'CustomerDashboardController@home');
});


Route::get('pay_success', 'PaymentController@success');
Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function() {
	Route::get('complains', 'AdminController@complain');
	Route::resource('seo', 'SeoController');
	Route::resource('servicecategories', 'ServiceCategoryAdminController');
	Route::resource('androidhomes', 'AndroidHomeController');
	Route::get('requests', 'AdminController@request');
	Route::get('slider_images','AdminController@slider_image');
	Route::get('userlists','AdminController@userlist');
	
	Route::get('home', 'AdminController@showhome');
	Route::resource('feedbacks', 'FeedbackController');
	Route::get('users', 'AdminController@showusers');
	Route::get('sendsms', 'AdminController@showsendsms');
	Route::resource('promocode', 'PromoCodeAdminController');
	Route::post('sendsms', 'AdminController@sendsms');

	//User list Routes
	Route::get('user-list','Admin\UserController@index');
	Route::get('add-user','Admin\UserController@create');
	Route::post('add-user','Admin\UserController@store');
	Route::get('edit-user/{id}','Admin\UserController@edit');
	Route::post('edit-user/{id}','Admin\UserController@update');
	Route::get('user-list/{id}','Admin\UserController@destroy');

	//Bar list Routes
	Route::get('bar-list','Admin\BarListController@index');
	Route::get('add-bar','Admin\BarListController@create');
	Route::post('add-bar','Admin\BarListController@store');
	Route::get('edit-bar/{id}','Admin\BarListController@edit');
	Route::post('edit-bar/{id}','Admin\BarListController@update');
	Route::get('bar-list/{id}','Admin\BarListController@destroy');

	//Menu list Routes
	Route::get('menu-list','Admin\MenuListController@index');
	Route::get('add-menu','Admin\MenuListController@create');
	Route::post('add-menu','Admin\MenuListController@store');
	Route::get('edit-menu/{id}','Admin\MenuListController@edit');
	Route::post('edit-menu/{id}','Admin\MenuListController@update');
	Route::get('menu-list/{id}','Admin\MenuListController@destroy');

	//Drink Type Routes
	Route::get('drink-type','Admin\DrinkTypeController@index');
	Route::get('add-drink','Admin\DrinkTypeController@create');
	Route::post('add-drink','Admin\DrinkTypeController@store');
	Route::get('edit-drink/{id}','Admin\DrinkTypeController@edit');
	Route::post('edit-drink/{id}','Admin\DrinkTypeController@update');
	Route::get('drink-type/{id}','Admin\DrinkTypeController@destroy');

	//Bookings Routes
	
	Route::get('bookings','Admin\BookingController@index');
	Route::get('add-booking','Admin\BookingController@create');
	Route::post('add-booking','Admin\BookingController@store');
	Route::get('edit-booking/{id}','Admin\BookingController@edit');
	Route::post('edit-booking/{id}','Admin\BookingController@update');
	Route::get('booking/{id}','Admin\BookingController@destroy');

	//Payments Routes
	Route::get('payments','Admin\PaymentController@index');
	Route::get('add-payment','Admin\PaymentController@create');
	Route::post('add-payment','Admin\PaymentController@store');
	Route::get('edit-payment/{id}','Admin\PaymentController@edit');
	Route::post('edit-payment/{id}','Admin\PaymentController@update');
	Route::get('payment/{id}','Admin\PaymentController@destroy');

});

Route::group(['prefix' => 'club', 'middleware' => ['care']], function() {
	Route::get('userlists','AdminController@userlist');
	
	Route::get('home', 'AdminController@showhome');
	Route::resource('feedbacks', 'FeedbackController');
	Route::get('users', 'AdminController@showusers');
	Route::get('sendsms', 'AdminController@showsendsms');
	Route::resource('promocode', 'PromoCodeAdminController');
	Route::post('sendsms', 'AdminController@sendsms');

	
	//Bar list Routes
	Route::get('bar-list','Admin\BarListController@index');
	Route::get('bar-list/{id}','Admin\BarListController@destroy');

	//Menu list Routes
	Route::get('menu-list','Admin\MenuListController@index');
	Route::get('add-menu','Admin\MenuListController@create');
	Route::post('add-menu','Admin\MenuListController@store');
	Route::get('edit-menu/{id}','Admin\MenuListController@edit');
	Route::post('edit-menu/{id}','Admin\MenuListController@update');
	Route::get('menu-list/{id}','Admin\MenuListController@destroy');

	
	
});
Route::get('privacy', 'StaticPageController@showprivacy');
Route::get('terms', 'StaticPageController@showterms');









//================ frontend route ==================
Route::get('/', 'FrontendController@index');
Route::get('/about', 'FrontendController@about');
Route::get('/admin1', 'FrontendController@admin');
Route::get('/home', 'FrontendController@index');
Route::get('index', 'FrontendController@index');
Route::get('brands', 'FrontendController@car_brand');
Route::get('accessories', 'FrontendController@accessories' );
Route::get('car_accessories', 'FrontendController@car_accessories');
Route::get('car_servicing', 'FrontendController@car_servicing');
Route::get('car_modification', function () {    return view('frontend/car_modification'); });
// Route::get('car_servicing', function () {    return view('frontend/car_servicing'); });
Route::get('car_wash', function () {    return view('frontend/car_wash'); });
Route::get('car_wrap', function () {    return view('frontend/car_wrap'); });
Route::get('contact_us', function () {    return view('frontend/contact_us'); });
// Route::get('brands', function () {return view('frontend/brands'); });

Route::get('package', 'FrontendController@car_packages');
Route::get('luxury','FrontendController@brand');
Route::get('luxury/{brand_name}','FrontendController@brand_data');

// Route::get('package', function () {    return view('frontend/package'); });
/*Route::get('bookpackage', function () {    return view('frontend/package_book'); });
*/
Route::get('shop_prod/{accesories_id}','FrontendController@shop_prod');
Route::get('support', function () {    return view('frontend/support'); });
Route::get('wash_pack', function () {    return view('frontend/wash_pack'); });
Route::get('policy', function () {    return view('frontend/policy'); });
Route::POST('complain/add_complain', 'FrontendController@complain_store');
Route::POST('request/add_request', 'FrontendController@requests_store');
Route::POST('request/call_back', 'FrontendController@callback_store');
Route::POST('submit_contact', 'FrontendController@contact_store');
Route::get('wash_pack/{service}/{category}', 'FrontendController@choosebrand');
Route::get('getmodel/{brand_id}', 'FrontendController@model_data');
Route::get('getmodel2/{brand_id}', 'FrontendController@model_data2');
Route::POST('getpackages', 'FrontendController@package_data');
Route::POST('getserform', 'FrontendController@getserform');
Route::POST('shop/ondemand_req', 'FrontendController@ondemand');
Route::POST('package_req', 'FrontendController@package');
Route::POST('package_form', 'FrontendController@package_form');

Auth::routes();
Route::POST('book_your_package', 'HomeController@done_booking');
Route::get('/book_package/{pack_id}/{model_id}', 'HomeController@bookPackage');

Route::POST('update/user_profile', 'HomeController@user_profile')->name('home');
Route::POST('update/password', 'HomeController@changePassword')->name('home');
Route::POST('home/wallet/add_money', 'WalletController@addBalance')->name('add_money');
Route::get('event-registration', 'PayTMController@register');
Route::get('paytm/carwash/{id}/{booking}', 'PayTMController@customerpayment');
Route::post('payment', 'PayTMController@order');

resources/views/admin/accessories.blade.php
@extends('layouts.'.Auth::user()->user_type)


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Accessories List <a href="{{ url('admin/accessories/create')}}" class="btn btn-primary btn-xs">Add Accessory</a></h4>
@if(Session::has('message'))
   <div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
<table id="datatable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Image</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        <?php $i=1; ?>
        
        	@foreach ($accessories as $accessory)
            <tr>
                <td> {{ $i }}</td>
                <td>{{ $accessory->name }}</td>
                <td>
                   {{--  <?php 
                        $data[] = $saccessory->image[]; 
                    ?> 
                    @foreach()
                    <img src="{{ asset('images/accessories/'.$accessory->image) }}" alt="" style="width: 100px; height: 50px;"> --}}

                </td>
                <td>{{ $accessory->description }}</td>
                <td>
                    {{ link_to_route('accessories.edit','Edit',[$accessory->id], ['class'=> 'btn btn-primary btn-xs col-md-2']) }}

                        {!! Form::open(['method'=>'delete','route'=>['accessories.destroy', $accessory->id],'class'=>'col-md-6' ]) !!}

                    {!! Form::submit('Delete',['class'=>'btn btn-danger btn-xs' ])!!}{!! Form::close() !!} 
               </td>
            </tr>
            <?php $i++; ?> 
            @endforeach
        @endif
       
    </tbody>
</table>                    
@endsection

resources/views/admin/add_accessory.blade.php
@extends('layouts.'.Auth::user()->user_type)


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Add Accessory</h4>
@if(isset($success))
    <div class="alert alert-success"> {{$success}} </div>
@endif
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(isset($accessories))
    {{ Form::model($accessories, ['route' => ['accessories.update', $accessories->id],'class'=>'form-horizontal', 'files' => true, 'method' => 'patch']) }}
@else

    {!!  Form::open(array('route' =>'accessories.store','class'=>'form-horizontal','files' => true )) !!}

@endif
                                        
                                        
                <div class="form-group">
                    {!! Form::label('title','Name :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::text('name',Input::old('name'),['class'=>'form-control'])!!}
                    </div>
                </div>
                <div class="form-group">
                    {!! Form::label('title','Description :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::text('description',Input::old('description'),['class'=>'form-control'])!!}
                    </div>
                </div>
                
                <div class="form-group">
                    {!! Form::label('title','Image :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::file('image[]',['class'=>'form-control','multiple'],Input::old('image')) !!}
                    </div>
                </div>	
               
                <div class="form-group">
                    <div class="col-sm-6 col-sm-offset-5">
                        {!! Form::submit('submit',array('class' => 'btn btn-primary'))!!}
                    </div>
                </div>


            {!! Form::close() !!}                  
                                         


                        

                    
@endsection

resources/views/admin/add_android_home.blade.php
@extends('layouts.'.Auth::user()->user_type)


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Add Banner Images</h4>
@if(isset($success))
    <div class="alert alert-success"> {{$success}} </div>
@endif
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(isset($androidhome))
    {{ Form::model($androidhome, ['route' => ['androidhomes.update', $accessories->id],'class'=>'form-horizontal', 'files' => true, 'method' => 'patch']) }}
@else

    {!!  Form::open(array('route' =>'androidhomes.store','class'=>'form-horizontal','files' => true )) !!}

@endif
                                        
                                        
                <div class="form-group">
                    {!! Form::label('title','URL :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::text('banner_url',Input::old('banner_url'),['class'=>'form-control'])!!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('title','Image :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::file('banner_image',['class'=>'form-control','multiple'],Input::old('banner_image')) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('title','Intent :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::text('intent',Input::old('intent'),['class'=>'form-control'])!!}
                    </div>
                </div>
                
                <div class="form-group">
                    {!! Form::label('title','Type :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {{ Form::select('type', 
                                        [ 'banner' => 'Banner', 
                                          'grid' => 'Grid',
                                          'rsa' => 'RSA',
                                    ],Input::old('type'),['class'=>'form-control'] ) }}
                    </div>
                </div>
                	
               
                <div class="form-group">
                    <div class="col-sm-6 col-sm-offset-5">
                        {!! Form::submit('submit',array('class' => 'btn btn-primary'))!!}
                    </div>
                </div>


            {!! Form::close() !!}                  
                                         


                        

                    
@endsection

resources/views/admin/add_booking.blade.php
@extends('layouts.care')


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Add Car Wash Booking </h4>
@if(isset($success))
    <div class="alert alert-success"> {{$success}} </div>
@endif
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif     
       {{-- @if(isset($car_wash))
    {{ Form::model($car_wash, ['route' => ['car_wash.update', $car_wash->id],'class'=>'form-horizontal', 'files' => true, 'method' => 'patch']) }}
@else

    {!!  Form::open(array('route' =>'car_wash.store','class'=>'form-horizontal','files' => true )) !!}

@endif --}}

        <form action="/admin/book_car_wash" method="POST" class="form-horizontal" >
            {{ csrf_field() }}
            
        <div class="form-group">
            {!! Form::label('title','Mobile :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('mobile',Input::old('mobile'),['class'=>'form-control', 'id' => 'mobile'])!!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('title','First Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('firstname',Input::old('firstname'),['class'=>'form-control'])!!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title','Last Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('lastname',Input::old('lastname'),['class'=>'form-control'])!!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title','Email :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('email',Input::old('email'),['class'=>'form-control'])!!}
            </div>
        </div>
        

        <div class="form-group">
            {!! Form::label('title','Package Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('package_id', 
                                $packages,Input::old('package_id'),['class'=>'form-control'] ) }}
            </div>
        </div>
        

        <div class="form-group">
            {!! Form::label('title','Brand Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('brand_id', 
                                $brands,Input::old('brand_id'),['class'=>'form-control'] ) }}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title','Model Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('model_id', 
                                $carmodels,Input::old('model_id'),['class'=>'form-control'] ) }}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title','Car Category :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('car_type', 
                                [ 'hatchback' => 'Hatchback', 
                                  'sedan' => 'Sedan',
                                  'suv' => 'Suv',
                                  'compact suv' => 'Compact Suv',
                                  'premium' => 'Premium',
                                  'other' => 'Other'
                                ],Input::old('car_type'),['class'=>'form-control'] ) }}
            </div>
        </div>

        
        
       {{--  <div class="form-group">
            {!! Form::label('title','Package Image :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::file('package_img',Input::old('brand_img'),['class'=>'form-control'])!!}
            </div>
        </div>	 --}}
       
        <div class="form-group">
            <div class="col-sm-6 col-sm-offset-5">
                {!! Form::submit('submit',array('class' => 'btn btn-primary'))!!}
            </div>
        </div>


    {!! Form::close() !!}                  
                        


                        


                        

                    
@endsection

resources/views/admin/add_car_wash.blade.php
@extends('layouts.'.Auth::user()->user_type)


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Add Car Wash Package </h4>
@if(isset($success))
    <div class="alert alert-success"> {{$success}} </div>
@endif
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif     
       @if(isset($car_wash))
    {{ Form::model($car_wash, ['route' => ['car_wash.update', $car_wash->id],'class'=>'form-horizontal', 'files' => true, 'method' => 'patch']) }}
@else

    {!!  Form::open(array('route' =>'car_wash.store','class'=>'form-horizontal','files' => true )) !!}

@endif



        <div class="form-group">
            {!! Form::label('title','Package Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('package_name',Input::old('package_name'),['class'=>'form-control'])!!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('title','Package Category :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('package_category', 
                				[ 'hatchback' => 'Hatchback', 
                				  'sedan' => 'Sedan',
                                  'suv' => 'Suv',
                                  'compact suv' => 'Compact Suv',
                                  'premium' => 'Premium',
                                  'other' => 'Other'
                				],Input::old('package_category'),['class'=>'form-control'] ) }}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('title','Package Type :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('package_type', 
                				[ 
                				  'monthly' => 'Monthly',
                				  'quarterly' => 'Quarterly',
                				  'halfyearly' => 'Half-Yearly',
                				  'yearly' => 'Yearly'
                				],Input::old('package_type'),['class'=>'form-control'] ) }}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('title','Package Amount :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('package_price',Input::old('package_price'),['class'=>'form-control'])!!}
            </div>
        </div>
        <div class="form-group">
        	{{-- <label for="" class="col-sm-3 control-label">Description</label>
        	<div class="col-sm-6">
        		
			<textarea class="ckeditor" name="package_desc">{{ Input::old('package_desc') }}</textarea>
        	</div> --}}
            {!! Form::label('title','Description :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::textarea('package_desc',Input::old('package_desc'),['class'=>'ckeditor'])!!}
            </div>
        </div>
        
       {{--  <div class="form-group">
            {!! Form::label('title','Package Image :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::file('package_img',Input::old('brand_img'),['class'=>'form-control'])!!}
            </div>
        </div>	 --}}
       
        <div class="form-group">
            <div class="col-sm-6 col-sm-offset-5">
                {!! Form::submit('submit',array('class' => 'btn btn-primary'))!!}
            </div>
        </div>


    {!! Form::close() !!}                  
                        


                        


                        

                    
@endsection

resources/views/admin/android_home.blade.php
@extends('layouts.'.Auth::user()->user_type)


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Banner Images</h4>
@if(Session::has('message'))
   <div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
<table id="datatable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>URL</th>
            <th>Picture</th>
            <th>Intent</th>
            <th>Type</th>
        </tr>
    </thead>

    <tbody>
        <?php $i=1; ?>
    	@foreach ($android_homes as $data)
        <tr>
            <td>{{ $i }}</td>
            <td>{{ $data->banner_url }}</td>
            <td>{{ $data->banner_image }}</td>
            <td>{{ $data->intent }}</td>
            <td>{{ $data->type }}</td>
            
            <td>
                {{-- {{ link_to_route('data.edit','Edit',[$data->id], ['class'=> 'btn btn-primary btn-xs']) }} --}}

                    {{-- {!! Form::open(['method'=>'delete','route'=>['complain_destroy', $data->id]]) !!} --}}

                {{-- {!! Form::submit('Delete',['class'=>'btn btn-danger btn-xs' ])!!}{!! Form::close() !!}  --}}
           </td>
        </tr>
        <?php $i++; ?>
        @endforeach
       
    </tbody>
</table>                    
@endsection

resources/views/admin/seo.blade.php
@extends('layouts.'.Auth::user()->user_type)


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Car List &nbsp; <a href="{{ url('admin/cars/create')}}" class="btn btn-primary btn-xs">Add Car</a></h4>
@if(Session::has('message'))
   <div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
<table id="datatable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Page Name</th>
            <th>Keywords</th>
            <th>Meta description</th>
            <th>Tags</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        <?php $i=1; ?>
    	@foreach ($seo as $data)
        <tr>
            <td> {{ $i }}</td>
            <td>{{ $data->title }}</td>
            <td>{{ $data->page_name }}</td>
            <td>{{ $data->keywords }}</td>
            <td>{{ $data->meta_desc }}</td>
            <td>{{ $data->tags }}</td>
            <td>
                {{ link_to_route('seo.edit','Edit',[$data->id], ['class'=> 'btn btn-primary btn-xs col-md-4']) }}                
           </td>
        </tr>
        <?php $i++; ?> 
        @endforeach
       
    </tbody>
</table>                    
@endsection

resources/views/admin/vehicle.blade.php
@extends('layouts.'.Auth::user()->user_type)


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Promocode List</h4>
@if(Session::has('message'))
   <div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
<table id="datatable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>status</th>
            <th>promo_code</th>
            <th>usable</th>
            <th>amount</th>
            <th>promo_type</th>
            <th>usage_type</th>
            <th>user_id</th>
            <th>expiry_date date</th>
            <th>message</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
    	@foreach ($data as $promocode)
        <tr>
            <td>{{ $promocode->status }}</td>
            <td>{{ $promocode->promo_code }}</td>
            <td>{{ $promocode->usable }}</td>
            <td>{{ $promocode->amount }}</td>
            <td>{{ $promocode->promo_type }}</td>
            <td>{{ $promocode->usage_type }}</td>
            <td>{{ $promocode->user_id }}</td>
            <td>{{ $promocode->expiry_date }}</td>
            <td>{{ $promocode->message }}</td>
            <td>
                {{ link_to_route('promocode.edit','Edit',[$promocode->id], ['class'=> 'btn btn-primary btn-xs']) }}

                    {!! Form::open(['method'=>'delete','route'=>['promocode.destroy', $promocode->id]]) !!}

                {!! Form::submit('Delete',['class'=>'btn btn-danger btn-xs' ])!!}
                {!! Form::close() !!} 
           </td>
        </tr>
        @endforeach
       
    </tbody>
</table>                    
@endsection